name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Launcher3
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        
      - name: Build Launcher3 Release
        run: ./gradlew assembleRelease

      - name: Upload debug app
        uses: actions/upload-artifact@v4
        with:
          name: launcher3-debug
          path: app/build/outputs/apk/debug/
